sudo: enabled
language: python
script: python main.py
addons:
  chrome: stable
before_script:
  - wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/bin
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3